---

- name: install
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - haproxy

- name: config
  template:
    src:  haproxy.cfg.j2
    dest: "{{ haproxy_config_file }}"
  notify:
    - restart haproxy

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - haproxy
