---

- name: install apt packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  with_items:
    - haproxy

- name: config
  template:
    src: haproxy.cfg.j2
    dest: "{{ haproxy_config_file }}"
  notify:
    - restart haproxy
  tags: haproxy_config

- name: service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - haproxy
