---

- name: restart haproxy
  command: "haproxy -c -f {{ haproxy_config_file }}"
  changed_when: true
  notify:
    - do restart haproxy

- name: do restart haproxy
  service:
    name:  haproxy
    state: restarted
